# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Singular Value Thresholding on a numeric matrix
#' 
#' @param X numeric matrix
#' @param penalty scalar to penalize singular values 
#' @return a list with 2 components, the singular value thresholded matrix and its thresholded singular values
#' @export
RcppSVT <- function(X, penalty) {
    .Call('RAD_RcppSVT', PACKAGE = 'RAD', X, penalty)
}

RcppSoftThresholdScalar <- function(x, penalty) {
    .Call('RAD_RcppSoftThresholdScalar', PACKAGE = 'RAD', x, penalty)
}

RcppSoftThresholdVector <- function(x, penalty) {
    .Call('RAD_RcppSoftThresholdVector', PACKAGE = 'RAD', x, penalty)
}

RcppSoftThresholdMatrix <- function(x, penalty) {
    .Call('RAD_RcppSoftThresholdMatrix', PACKAGE = 'RAD', x, penalty)
}

#' Robust Principal Component Pursuit
#' 
#' @param X numeric matrix
#' @param Lpenalty scalar to penalize singular values. 
#' A default of -1 is used as a sentinel value. Under this sentinel value
#' a smart thresholding algorithm sets the value of Lpenalty, so the user does not need to.
#' @param Spenalty scalar to penalize remainder matrix to find anomalous values.
#' A default of -1 is used as a sentinel value. Under this sentinel value
#' a smart thresholding algorithm setes the value of Spenalty, so the user does not need to.
#' @return a list with 4 matrices.  X is decomposed into L + S + E where L is low rank,
#' S is sparse and E is the remainder matrix of noise
#' @importFrom Rcpp evalCpp
#' @export
RcppRPCA <- function(X, Lpenalty = -1, Spenalty = -1, verbose = FALSE) {
    .Call('RAD_RcppRPCA', PACKAGE = 'RAD', X, Lpenalty, Spenalty, verbose)
}

